# dependabot.yml file to upgrade envd package dependency

# see also [dep_trig_release.yml]

version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "daily"
    allow:
      # Only allow updates for envd
      - dependency-name: "github.com/tensorchord/envd"