builds:
- id: linux-build
  main: ./cmd/envd-lsp
  env:
  - CGO_ENABLED=1
  goos:
  - linux
  goarch:
    - amd64
  ignore:
  - goos: linux
    goarch: 386
  ldflags:
    - -s -w
    - -X github.com/tensorchord/envd-lsp/pkg/version.version={{ .Version }}
    - -X github.com/tensorchord/envd-lsp/pkg/version.buildDate={{ .Date }}
    - -X github.com/tensorchord/envd-lsp/pkg/version.gitCommit={{ .Commit }}
    - -X github.com/tensorchord/envd-lsp/pkg/version.gitTreeState=clean
- id: darwin-build
  main: ./cmd/envd-lsp
  ldflags:
    - -s -w
    - -X github.com/tensorchord/envd-lsp/pkg/version.version={{ .Version }}
    - -X github.com/tensorchord/envd-lsp/pkg/version.buildDate={{ .Date }}
    - -X github.com/tensorchord/envd-lsp/pkg/version.gitCommit={{ .Commit }}
    - -X github.com/tensorchord/envd-lsp/pkg/version.gitTreeState=clean
  env:
  - CGO_ENABLED=1
  - PKG_CONFIG_SYSROOT_DIR=/sysroot/macos/amd64
  - PKG_CONFIG_PATH=/sysroot/macos/amd64/usr/local/lib/pkgconfig
  - CC=o64-clang
  - CXX=o64-clang++
  goos:
  - darwin
  goarch:
    - amd64
    - arm64
  ignore:
  - goos: darwin
    goarch: 386
# https://goreleaser.com/customization/universalbinaries/?h=universal_binaries
universal_binaries:
  - replace: true
    id: darwin-build
archives:
  - id: linux-build
    format: binary
    builds:
      - linux-build
    name_template: "{{ .ProjectName }}_Linux_x86_64"
  - id: darwin-build
    format: binary
    builds:
      - darwin-build
    name_template: "{{ .ProjectName }}_Darwin_all"
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^build:'
      - '^ci:'
      - '^docs:'
      - '^test:'
      - '^chore:'
