builds:
- id: linux-build
  main: ./cmd/envd-lsp
  env:
  - CGO_ENABLED=1
  goos:
  - linux
  goarch:
    - amd64
  ignore:
  - goos: linux
    goarch: 386
- id: darwin-build
  main: ./cmd/envd-lsp
  ldflags:
  - -s
  env:
  - CGO_ENABLED=1
  - PKG_CONFIG_SYSROOT_DIR=/sysroot/macos/amd64
  - PKG_CONFIG_PATH=/sysroot/macos/amd64/usr/local/lib/pkgconfig
  - CC=o64-clang
  - CXX=o64-clang++
  goos:
  - darwin
  goarch:
    - amd64
  ignore:
  - goos: darwin
    goarch: 386
