# dep_trig_release.yml file will merge it when 
# the dependabot updates envd and creates a PR,
# then push a tag to trigger a release

# see also [dependabot.yml]

name: dependabot trigger release
on:
  pull_request:

permissions:
  pull-requests: write
  contents: write

jobs:
  dependabot-auto-merge:
    name: Merge a dependabot PR
    runs-on: ubuntu-latest
    # Checking the actor will prevent your Action run failing on non-Dependabot
    # PRs but also ensures that it only does work for Dependabot PRs.
    if: github.actor == 'dependabot[bot]'
    steps:
    # The step will fail if there's no metadata and so the approval will not occur.
    - name: Dependabot metadata
      id: dependabot-metadata
      uses: dependabot/fetch-metadata@v1.3.5
      with:
        github-token: "${{ secrets.GITHUB_TOKEN }}"
    - name: Approve PR
      run: gh pr review --approve "$PR_URL"
      env:
        PR_URL: ${{ github.event.pull_request.html_url }}
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Enable auto-merge for Dependabot PRs
      run: gh pr merge --auto --squash "$PR_URL"
      env:
        PR_URL: ${{ github.event.pull_request.html_url }}
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  dependabot-push-tag:
    name: Push a tag for dependabot PR
    runs-on: ubuntu-latest
    # Push a tag happens when a PR of dependabot is merged
    needs: dependabot-auto-merge
    steps:
    - uses: actions/checkout@v3
    - name: Dependabot metadata
      id: dependabot-metadata
      uses: dependabot/fetch-metadata@v1.3.5
      with:
        github-token: "${{ secrets.GITHUB_TOKEN }}"
    - name: Bump version and push tag
      id: tag_version
      uses: mathieudutour/github-tag-action@v6.1
      with:
        custom_tag: ${{ steps.dependabot-metadata.outputs.new-version }}
        github_token: ${{ secrets.GITHUB_TOKEN }}
  dependabot-release: 
    needs: dependabot-push-tag
    uses: ./.github/workflows/release.yml