# dep_pub_tag.yml file will push a tag according to 
# the version of envd when the dependabot PR is merged.

# see also [dep_auto_merge.yml] and [dependabot.yml]

name: dependabot push tag

on:
  pull_request:
    types:
      - closed

jobs:
  dependabot-push-tag:
    name: Push a tag for dependabot PR
    runs-on: ubuntu-latest
    # Push a tag happens when a PR of dependabot is merged
    if: {{ (github.actor == 'dependabot[bot]') && (github.event.pull_request.merged == true) }}
    steps:
    - name: Dependabot metadata
      id: dependabot-metadata
      uses: dependabot/fetch-metadata@v1.3.5
      with:
        github-token: "${{ secrets.GITHUB_TOKEN }}"
    - name: Bump version and push tag
      uses: anothrNick/github-tag-action@1.52.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        CUSTOM_TAG : ${{ steps.dependabot-metadata.outputs.new-version }}