name: release

on:
  workflow_call:
  push:
    tags:
      - 'v*'

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: 'main'
          fetch-depth: 0
      - name: Show tags
        run: git tag
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.18
      - name: setup release environment
        run: |-
          echo 'GITHUB_TOKEN=${{secrets.GITHUB_TOKEN}}' > .release-env
      - name: Run GoReleaser
        run: make release
